services:
  postgres:
    image: postgres:16
    container_name: bttyPostgres_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: bttyAdmin123
      POSTGRES_DB: btty_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: